name = "s3-to-r2"
compatibility_date = "2022-05-12"
main = "./src/index.ts"

routes = [
    { pattern = "data.openaddresses.io/*", zone_id = "1589a7a76f5cb624e26d19b16c3143a1" },
    { pattern = "results.openaddresses.io/*", zone_id = "1589a7a76f5cb624e26d19b16c3143a1" },
    { pattern = "v2.openaddresses.io/*", zone_id = "1589a7a76f5cb624e26d19b16c3143a1" },
]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[vars]
AWS_DEFAULT_REGION = "us-east-1"
AWS_SERVICE = "s3"
AWS_S3_BUCKET_SCHEME = 'https:'
AWS_S3_BUCKET = "v2.openaddresses.io"
R2_OBJECT_PREFIX = "v2.openaddresses.io"
R2_BUCKET_NAME = "openaddresses"

[[r2_buckets]]
binding = 'R2'
bucket_name = 'openaddresses'

[[kv_namespaces]]
binding = "OA_USAGE"
id = "a1f4c7c4e9e9438b9a49d52f5a76c11d"
